#!/bin/bash
set -eux

ddl_dir=$(dirname $0)/../ddl

echo $DATABASE_URL

# A script to initialise the database.
#
# Install postgres and postgis.
# There are comprehensive instructions here http://wiki.openstreetmap.org/wiki/Mapnik/PostGIS
#
# Set the default timezone to UTC and set the timezone abbreviations.
# Assuming a yum install this will be `/var/lib/pgsql/data/postgresql.conf`
# ...
# timezone = UTC
# timezone_abbreviations = 'Default'
#
# For testing do not set a password for postgres and in /var/lib/pgsql/data/pg_hba.conf set
# connections for local ans host connections to trust:
#
# local   all             all                                     trust
# host    all             all             127.0.0.1/32            trust
#
# Restart postgres.
#
#
# Basic UTF8 postgres DB
#
dropdb --host=127.0.0.1 hazard
dropuser --host=127.0.0.1 geonetadmin
dropuser --host=127.0.0.1 hazard_w

# This will be our database admin user - it's not a superuser and shouldn't need to be.
createuser --host=127.0.0.1 --createdb --createrole geonetadmin

# Will be the database writer user - needed for unit tests.  Mule will need more privileges than this user.
createuser --host=127.0.0.1 --username=geonetadmin hazard_w

createdb --host=127.0.0.1 --username=geonetadmin -E UTF8 --template=template0 hazard

# Make sure the timezone is UTC for the hazard DB.  Redundant for GeoNet hosts
# but may be important for AWS RDS.
psql --host=127.0.0.1 -d hazard -U geonetadmin -c 'ALTER DATABASE hazard SET timezone TO UTC;'

# Function security means adding postgis has to be done as a superuser - here that is the postgres user.
# On AWS RDS the created functions have to be transfered to the rds_superuser.
# http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.html#Appendix.PostgreSQL.CommonDBATasks.PostGIS
psql --host=127.0.0.1 -d hazard -c 'create extension postgis;'

psql --host=127.0.0.1 --quiet --username=geonetadmin --dbname=hazard --file=${ddl_dir}/qrt-drop-create.ddl
psql --host=127.0.0.1 --quiet --username=geonetadmin hazard -f ${ddl_dir}/user-permissions.ddl
